name: Verify CMSIS Compliance QeexoAutoML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-cmsis-compliance-QeexoAutoML:
    name: Verify CMSIS Compliance QeexoAutoML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Arm-Examples/verify-cmsis-example-action@latest
        name: Verify CMSIS Compliance QeexoAutoML
        with:
          branch: ${{ github.ref }}
          project-file: ./QeexoAutoML/MLOps.csolution.yml
          API_TOKEN: ${{ secrets.CMSIS_API_KEY }}
          output-artifact: output-QeexoAutoML
